defaults:                       ### This code is to run for slurm config
    - dominik_kitti_360_base
    - _self_

#### Simply comment one of them for usage. (Because we want the same configuration as the model was trained last time.)

## For training
name: "BaseExperimentFeatureFusion" 

model_conf:
    decoder_heads:
        - type: "MultiViewHead3"
          name: "multiviewhead"
          freeze: false
          args:
            mlp:
                type: "resnet"
                args:
                    n_blocks: 0
                    d_hidden: 64
            mlp:
                type: "resnet"
                d_in: 4
                args:
                    n_blocks: 0
                    d_hidden: 4
            dropout_views_rate: 0.5
            dropout_multiviewhead: true
